# Generated by Django 4.1.3 on 2022-12-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("overview", models.TextField(blank=True, null=True)),
                ("popularity", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vote_average",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vote_count", models.CharField(blank=True, max_length=100, null=True)),
                ("video", models.BooleanField(blank=True, null=True)),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
