# Generated by Django 4.1.3 on 2022-12-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviedata",
            name="slug",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
